/*
 * VHDLGenerator.h
 *
 *  Created on: 14 June 2021
 *      Author: jkmingwen
 */

#ifndef VHDL_GENERATOR_H_
#define VHDL_GENERATOR_H_

#include <algorithms/schedulings.h>
#include <commons/KiterRegistry.h>
#include "VHDLCircuit.h"
#include "VHDLConnection.h"
#include "VHDLComponent.h"

VHDLCircuit generateCircuitObject(models::Dataflow *const dataflow, implType = TT);
std::string binaryValue(VHDLComponent const comp);

namespace models {
  class Dataflow;
}

namespace algorithms {
  void generateVHDL(models::Dataflow* const dataflow,
                                 parameters_list_t);
  void generateOperators(const VHDLCircuit &circuit);
  void generateFPCOperator(std::string compImplementationName);

  void generateCircuit(VHDLCircuit &circuit);
  void generateHSInterfaceComponents();
  void generateAudioInterfaceComponents();
  void printCircuitInfo(models::Dataflow* const dataflow,
                        parameters_list_t param_list);
  void printOperatorCounts(models::Dataflow *const dataflow,
                           parameters_list_t param_list);
}

ADD_TRANSFORMATION(GenerateVHDL,
                   transformation_t({ "GenerateVHDL" , "Generate VHDL from SDF.", algorithms::generateVHDL}));
ADD_TRANSFORMATION(PrintCircuitInfo,
                   transformation_t({ "PrintCircuitInfo" , "Print information about VHDL components that would be generated by GenerateVHDL.", algorithms::printCircuitInfo}));

ADD_TRANSFORMATION(PrintOperatorCounts,
                   transformation_t({ "PrintOperatorCounts" , "Print information about VHDL components that would be generated by GenerateVHDL.", algorithms::printOperatorCounts}));

#endif /* VHDL_GENERATOR_H_ */
